# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"2\n\x12instructionRequest\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\r\n\x05query\x18\x01 \x01(\t\"\"\n\x0fmessageResponse\x12\x0f\n\x07results\x18\x01 \x03(\t2D\n\x0emessageService\x12\x32\n\x07message\x12\x13.instructionRequest\x1a\x10.messageResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSTRUCTIONREQUEST._serialized_start=18
  _INSTRUCTIONREQUEST._serialized_end=68
  _MESSAGERESPONSE._serialized_start=70
  _MESSAGERESPONSE._serialized_end=104
  _MESSAGESERVICE._serialized_start=106
  _MESSAGESERVICE._serialized_end=174
# @@protoc_insertion_point(module_scope)
